### ISSUE TITLE
apt is standard versus apt-get from this write up. 

### ISSUE THREAD

**Issue by softwarepronto** [MicrosoftDocs/WSL#1430] opened 2022-01-22 08:09 UTC
`apt-get is used twice in the writeup. apt-get has been replaced by apt. apt-get is the old way -- just get ride of the -get from the page.`
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 782a4458-6a56-63e5-efaf-d1868762ed06
* Version Independent ID: 312f71d9-db7d-52a5-b03d-9b6d4c680c2a
* Content: [Get started using VS Code with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode)
* Content Source: [WSL/tutorials/wsl-vscode.md](https://github.com/MicrosoftDocs/wsl/blob/main/WSL/tutorials/wsl-vscode.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment] 2022-01-25 22:12
This is a duplicate of this issue: https://github.com/MicrosoftDocs/WSL/issues/1432

**Closed by craigloewen-msft** 2022-01-25 22:12 UTC
