### ISSUE TITLE
No link for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by SubhanRaj** [MicrosoftDocs/WSL#1540] opened 2022-06-05 03:15 UTC
### Documentation Issue

On the page [https://docs.microsoft.com/en-us/windows/wsl/install-manual](url)  there is no link and no mention of the available Ubuntu 22.04 LTS Version, it's still only up to Ubuntu 20.04 LTS.

### Link to documentation page

[https://docs.microsoft.com/en-us/windows/wsl/install-manual](url)

### Suggested Improvements

Just add the link and some Screenshot also of Ubuntu 22.04 LTS available on Microsoft store here: [https://apps.microsoft.com/store/detail/ubuntu-2204-lts/9PN20MSR04DW](url)

**Comment by Biswa96** [comment] 2022-06-05 03:18
Duplicate of https://github.com/MicrosoftDocs/WSL/issues/1507

**Comment by craigloewen-msft** [comment] 2022-06-20 17:39
Fixed!

**Closed by craigloewen-msft** 2022-06-20 17:39 UTC
