### ISSUE TITLE
invoke-rc.d: could not determine current runlevel

### ISSUE THREAD

**Issue by corykroll** [MicrosoftDocs/WSL#1033] opened 2020-12-22 21:12 UTC
Unable to install mySQL server.

I get an error of 'invoke-rc.d: could not determine current runlevel'
Subsequent running of mysql_secure_installation gets me:
Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 080023f0-501e-b638-b22c-9d2cbcbdb66a
* Version Independent ID: 88516d79-15be-0cf2-bb25-d20a17d1a37e
* Content: [Get started using MySQL MongoDB, PostgreSQL, SQLite, Microsoft SQL Server, or Redis to set up a database on Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database)
* Content Source: [WSL/tutorials/wsl-database.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/wsl-database.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment] 2021-06-03 18:17
Hi @corykroll - thanks for filing this, it looks like the issue is addressed in the WSL product repo, here: https://github.com/microsoft/WSL/issues/1761, so I'm going to close this as it currently doesn't look like something requiring a doc update. Please reopen if that's not the case.

It looks like this was a popular resolution posted by caseyallen386 you could try:

```
sudo su
apt-get remove --purge 'mysql*'
apt-get autoremove
apt-get autoclean
rm -f /etc/mysql /var/lib/mysql
apt-get install mysql-server
```

Thanks again!

**Closed by mattwojo** 2021-06-03 18:17 UTC
