### ISSUE TITLE
GUI Method

### ISSUE THREAD

**Issue by Josque** [MicrosoftDocs/WSL#282] opened 2018-10-10 07:55 UTC
I tried this method, but got the next message:
"'Enable-WindowsOptionalFeature' is not recognized as an internal or external command,operable program or batch file."
If you have the same problem you can use the GUI method instead: Start &gt;&gt; Windows Features &gt;&gt; Turn Windows Features on or off &gt;&gt; checkbox 'Windows Subsystem for Linux'. After that your PC will ask you to reboot.

Good luck and have fun using the Linux distro under Windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by 0not** [comment] 2018-10-13 17:28
From that error message it looks like you tried using the Command Prompt instead of PowerShell.

**Comment by ThinkingMonkeyv2** [comment] 2018-10-25 16:07
Actually it's the error message you get when you're not running admin PowerShell. (Right-click > Run as administrator)

**Comment by DarthSpock** [comment] 2019-01-02 21:13
@e3v3a that is not WSL related. I'd file it with the PS Core folks first

**Comment by E3V3A** [comment] 2019-01-03 11:00
@DarthSpock 
Sorry, I don't see how this is not WSL related. Seem exactly related to me. Please explain. 

Also, as you can see, I am not a developer for MS, so I am only reporting my findings.

**Comment by DarthSpock** [comment] 2019-01-03 13:43
Because PS Core is NOT Windows Powershell. It's made to be cross-platform. Therefore modules that are in Windows are not available by default in PS Core. They just released compatibility to utilize the builtin Windows PS modules just before the holiday so you can use commands typically found in Windows PS. That's why it's not a WSL actionable. The WSL team has no control or say in what the PS Core team does. I don't work for MS either but certain things should be obvious. It's possible the WSL team could do something on their end but that's time and resources being taken away from more important things like getting Docker, Fuse, and CUDA/OpenCL/Vulkan working for example. That's their focus and considering those are the biggest requests out there, I'd want them to stick with that, not reinvent how to install via PS, especially when they don't have any control over PS.

**Comment by E3V3A** [comment] 2019-01-03 16:37
Aha. This seem awfully confusing, but thanks for trying to explain. Never understood why you would call something `PowerShell Core`  but not being related to `PowerShell`. 

Anyway, the windows logo in your avatars and using repo *MicrosoftDocs* gave the impression that you are working for MS.

**Comment by DarthSpock** [comment] 2019-01-04 15:34
i was checking the docs and noticed more issues and used the lazy feature of signing into GitHub from MS Docs

**Comment by IcedZ** [comment] 2019-06-13 16:25
> Actually it only seem to work in the OS _original_ **powershell** admin. If you have updated to PS 6.1+ (using **pwsh**) you will get this error even if admin.

Confirmed - this was my problem.

**Comment by c3aus3scu** [comment] 2020-04-06 11:09
> From that error message it looks like you tried using the Command Prompt instead of PowerShell.

True ...

**Comment by WSLUser** [comment] 2020-04-06 12:41
PS7 should help if run in Administrator mode. It depreciated the Windows compatibility module and uses build-in compatibility support to utilize Windows Powershell modules. In other words, it shouldn't matter which PS you use now as long as you're using the stable LTS.

**Comment by mattwojo** [comment] 2020-09-25 18:15
Thanks for all of the helpful input and PowerShell context! Closing this issue as it appears to be resolved and not require a docs update.

**Closed by mattwojo** 2020-09-25 18:15 UTC
