### ISSUE TITLE
Missing download link for Debian 10 Buster Appx 

### ISSUE THREAD

**Issue by iranvir** [MicrosoftDocs/WSL#792] opened 2020-07-12 00:07 UTC
Hello, WSL Team!

Could you please add a link for Debian 10?
The link for Debian distro below is for Debian 9, and I can't seem to locate any other page or location for the Debian 10 Buster release, except in the Microsoft store.

For reference 
Debian 9 -->   PackageFullName   : TheDebianProject.DebianGNULinux_1.1.3.0_x64__76v4gfsz19hv4 
That is version 1.1.3.0 can be found at https://aka.ms/wsl-debian-gnulinux

Where as,
Debian 10 --> PackageFullName   : TheDebianProject.DebianGNULinux_1.1.8.0_x64__76v4gfsz19hv4
Version 1.1.8.0 needs to be added to the list (in the concerned documentation page).

Thank you so much for all your wonderful work related to WSL and WSL 2!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dimithras** [comment] 2020-08-29 20:36
While it's not provided, I've described a workaround in a comment to issue #877, [check](https://github.com/MicrosoftDocs/WSL/issues/877#issuecomment-683338384) it.

**Comment by tdashroy** [comment] 2021-02-25 21:07
This looks like a dupe of #563, @iranvir you might consider closing this one and giving that one a vote.

**Comment by craigloewen-msft** [comment] 2021-03-02 05:04
Updated the link! :)

**Closed by craigloewen-msft** 2021-03-02 05:04 UTC

**Comment by iranvir** [comment] 2021-03-02 07:06
Thanks a tonne!
