### ISSUE TITLE
Ubuntu 18 links aren't links

### ISSUE THREAD

**Issue by casterle** [MicrosoftDocs/WSL#585] opened 2020-03-11 22:20 UTC
Per the subject.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by michalkasparec** [comment] 2020-03-12 10:34
You can use modified 16.04 link
https://aka.ms/wsl-ubuntu-1804

**Comment by sinmeo** [comment] 2020-03-15 00:47
I am not sure if this is on purpose but that link is referring to the following domain: 
https://wsldownload.azureedge.net/ which as far as I am concerned no a legitimate microsoft domain.
I therefore do not recommend anyone downloading links referred to by anyone else.

**Comment by dev-bittlinger** [comment] 2020-03-17 08:59
Duplicate of #576

**Comment by TheFALSEGamer4** [comment] 2020-04-07 15:21
Sinmeo, I know that this is late and that you have already done your research. but azure is Microsoft's web service, kind of like amazon AWS.

**Closed** 2022-01-06 21:05 UTC
