### ISSUE TITLE
Migration Process and Information about it is lacking

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/WSL#190] opened 2018-04-28 02:55 UTC
Say, an user from the Anniversary Update wanted to jump to the 2018 April Update that's coming out in about a week, and the user wanted to preserve just the customized .bashrc file and a few other files. Where in the documentation articles for Windows Subsystem for Linux would it explains the migration process and the recommended way Microsoft gives out to end users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by bitcrazed** [comment] 2018-05-04 18:36
If you simply upgrade your PC from 1709 to 1803, you'll get the latest version of WSL but your distro instances remain untouched - we leave it up to you as to when/how you upgrade your distro instances themselves. 

If you plan on completely reinstalling Windows (rather than upgrading in-place), and want to keep some of your distro's files, then you'll need to copy the files you want to, for example:
1. Copy your files into a Windows folder (e.g. `/mnt/c/backups`) from which you can copy the files onto a USB stick or file-share
2. Copy your files from your distro onto a remote file store via, for example, ftp, etc.
3. Use any of the common Linux ecosystem backup strategies / tools, e.g.: https://superuser.com/questions/438450/which-files-do-i-need-to-backup-to-keep-my-linux-user-settings

**Comment by tommai78101** [comment] 2018-05-04 19:40
@bitcrazed  Could the information be added to the documentation?

**Comment by bitcrazed** [comment] 2018-05-04 19:45
We've considered this a few times, the issue is that the guidance differs for each distro, and the "best" approach differs for each user and scenario.

**Comment by craigloewen-msft** [comment] 2020-07-07 23:34
We've added an --export and --import command which should greatly help users migrate any distros in the future. I'll close this issue out, but feel free to reopen if you believe it's not addressed. Thank you for filing this! 

https://docs.microsoft.com/en-us/windows/wsl/reference#arguments-for-managing-windows-subsystem-for-linux

**Closed by craigloewen-msft** 2020-07-07 23:34 UTC
