### ISSUE TITLE
Update command gives me error on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Aman-rishu** [MicrosoftDocs/WSL#937] opened 2020-09-26 13:53 UTC
Note that this repo's issue tracker is only for reporting issues with the WSL docs.

Other related issue repo's:

* WSL: https://github.com/Microsoft/BashOnWindows/
* Windows Console: https://github.com/Microsoft/Console/
Whenever I run 
~$ sudo apt update && sudo apt upgrade
I get the error 
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

So please 
Anyone Help me!

**Comment by dimithras** [comment] 2020-09-28 18:48
Try `sudo ping 8.8.8.8` inside your distro (Ubuntu).
If you can not reach network, search for network related issues in wsl.
If network is reachable it's either dns problem or host being blocked by your network.
To check dns try `sudo ping archive.ubuntu.com`.

If only **archive.ubuntu.com** is not reachable, try changing your apt sources to some other mirror. There is plenty of info on how to do this in the web.

**Comment by Aman-rishu** [comment] 2020-09-29 03:16
It is also not working sir.
Its also shows the same error.

...

**Comment by dimithras** [comment] 2020-09-29 06:58
https://www.a2hosting.com/kb/getting-started-guide/internet-and-networking/troubleshooting-network-connectivity-with-ping-and-traceroute

**Comment by rebolloluis** [comment] 2020-10-08 00:56
Hello. I had a similar problem after changing my WSL default version to 2 (distro Ubuntu 20.04 LTS). I tried reinstalling the distro but the problem, persisted. Turns out Mcafee's firewall was blocking the requests; disabling it temporarily worked form me.

**Comment by JDRanpariya** [comment] 2021-01-18 05:11
First, temporarily add a known DNS server to your system.

`echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null`
Then run `sudo apt-get update.`

If this fixes your temporary resolving messages then either wait for 24 hours to see if your ISP fixes the issue for you (or just contact your ISP) - or you can permanently add a DNS server to your system:

`echo "nameserver 8.8.8.8" | sudo tee /etc/resolvconf/resolv.conf.d/base > /dev/null`
8.8.8.8  is Google's own DNS server.

[Source: ](https://askubuntu.com/questions/91543/apt-get-update-fails-to-fetch-files-temporary-failure-resolving-errorl)

**Comment by divyesh-inferenz-ai** [comment] 2021-01-31 06:25
@JDRanpariya  Thank you, this echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null    command works fine but I am getting error while make this change permanently as per your second command : echo "nameserver 8.8.8.8" | sudo tee /etc/resolvconf/resolv.conf.d/base > /dev/null


Error : tee: /etc/resolvconf/resolv.conf.d/base: No such file or directory

**Comment by areebaqamar021** [comment] 2021-02-04 02:14
I have seen the same issue anyone can help me?

**Comment by amegbor** [comment] 2021-03-12 12:44
@areebaqamar021 

the solution in the link below worked for me

https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6

**Comment by Abror1997** [comment] 2021-04-26 19:43
Windows defender may block the network as well. Disabling it solves the issue for me

**Comment by speed7861** [comment] 2021-04-27 18:23
> I have seen the same issue anyone can help me?

If it cant find the file then make it and set the correct path. I believe on ubuntu you can change the order from which linux checks for dns resolvers

**Comment by enweazudaniel** [comment] 2021-09-12 11:29
Try using a VPN

**Comment by jeremy-rutman** [comment] 2021-09-22 22:40
I am hitting similar issues, ultimately I blv due to this 

```
root@master:/home/ubuntu/tm_scrape_wipo# ping mirrors.kernel.org
ping: mirrors.kernel.org: Temporary failure in name resolution
root@master:/home/ubuntu/tm_scrape_wipo# ping archive.ubuntu.com
ping: archive.ubuntu.com: Temporary failure in name resolution
root@master:/home/ubuntu/tm_scrape_wipo# ping repos.insights.digitalocean.com
ping: repos.insights.digitalocean.com: Temporary failure in name resolution

```
any ideas why this would be ?

**Comment by avond** [comment] 2021-11-29 16:00
May be you masked or disable systemd-resolved.service?
try
`sudo systemctl unmask systemd-resolved.service
sudo systemctl enable systemd-resolved.service
sudo systemctl start systemd-resolved.service
sudo apt-get update`
Enjoy)

**Comment by Ibrahima-prog** [comment] 2021-12-09 08:57
> Try `sudo ping 8.8.8.8` inside your distro (Ubuntu). If you can not reach network, search for network related issues in wsl. If network is reachable it's either dns problem or host being blocked by your network. To check dns try `sudo ping archive.ubuntu.com`.
> 
> If only **archive.ubuntu.com** is not reachable, try changing your apt sources to some other mirror. There is plenty of info on how to do this in the web.

I changed my mirror from tr.archive.ubuntu.com to archive.ubuntu.com through this post:
https://askubuntu.com/questions/104695/how-do-i-change-mirrors-in-ubuntu-server-from-regional-to-main

Thank you.

**Comment by sangroya** [comment] 2021-12-22 00:50
This command solve problem for me: 

sudo systemctl restart systemd-resolved.service

**Comment by claudiumilea** [comment] 2022-01-09 12:40
> Hello. I had a similar problem after changing my WSL default version to 2 (distro Ubuntu 20.04 LTS). I tried reinstalling the distro but the problem persisted. Turns out, McAfee's firewall was blocking the requests; disabling it temporarily worked form me. See https://docs.microsoft.com/en-us/windows/wsl/faq#why-do-i-not-have-internet-access-from-wsl

you rule  ! this was it ! sneaky mcafee

**Comment by sreeramavipparti** [comment] 2022-01-25 07:07
sudo apt-get update --fix-missing 
Worked for me!

**Comment by siddharthtumre** [comment] 2022-02-12 12:13
Need help with this issue

**Comment by DanteLogan** [comment] 2022-02-23 22:08
> May be you masked or disable systemd-resolved.service? try `sudo systemctl unmask systemd-resolved.service` `sudo systemctl enable systemd-resolved.service` `sudo systemctl start systemd-resolved.service` `sudo apt-get update` Enjoy)

Holy shit this worked like a charm

**Comment by craigloewen-msft** [comment] 2022-03-03 21:05
Hi folks, networking issues can happen for a variety of reasons, and if you're seeing this issue please file it on the WSL Github repo at https://github.com/microsoft/wsl where the WSL devs can take a look and we'll have the necessary info to give actionable solutions! This repo is just for issues related to the docs. I'll close this issue for our bookkeeping. Thank you for filing!

**Closed by craigloewen-msft** 2022-03-03 21:05 UTC

**Comment by MattWanjia** [comment] 2022-03-21 08:08
> sudo systemctl restart systemd-resolved.service

This worked for me. Thanks

**Comment by sicrit1** [comment] 2022-04-19 11:01
I had that problem too. That problem caused by antivirus(Symantec Endpoint Protection). Turning off the Firewall saved me.

**Comment by EdoByco** [comment] 2022-05-30 14:16
I had this errore and i found out it was due to active VPN connection via FortiClient.
Disconnected VPN, retried -> worked. WSL2

**Comment by bishwasbh** [comment] 2022-06-24 14:01
Here's a pretty fast solution for [solving temporary failure resolving 'archive.ubuntu.com'](https://webmatrices.com/d/1030-temporary-failure-resolving-usarchiveubuntucom)

**Comment by AnouarDahdah** [comment] 2022-07-28 08:51
This happens to you maybe because of internet connection problem, so try this 👍 
1- edit the file " interfaces":
`sudo nano /etc/network/interfaces `

2- then make sure this line is in that file :
`iface eth0 inet dhcp`

3- run `dhclient`

4- run `ping 8.8.8.8`

**Comment by bkoprivica** [comment] 2022-08-09 21:45
> Here's a pretty fast solution for [solving temporary failure resolving 'archive.ubuntu.com'](https://webmatrices.com/d/1030-temporary-failure-resolving-usarchiveubuntucom)

Doesn't work

**Comment by d383746** [comment] 2022-08-15 08:15
> Here's a pretty fast solution for [solving temporary failure resolving 'archive.ubuntu.com'](https://webmatrices.com/d/1030-temporary-failure-resolving-usarchiveubuntucom)

Have spent 6 hours fighting with this issue. But your solution works. Very hard to understand what is going on. I was thinking it is a proxy issue, then network, but finally it was the content of the source.list. And it gets corrupted after a routine ubuntu update. Simple app but too hard to debug if it  gets broken. 
Thanks a lot for you help..

**Comment by Psychokiller1888** [comment] 2022-08-26 08:02
This is old I know, but came here for the same reason. For me, I had set my ethernet connection as fixed IP and had a typo in the DNS ip. After fixing it, all went back to normal

`sudo nano /etc/network/interfaces`

**Comment by Cjorozco** [comment] 2022-08-29 21:39
wsl --shutdown
# disconnect VPN
wsl
# connect VPN again3

**Comment by Meri-elizabeth** [comment] 2022-09-06 08:06
Try
**ufw disable**
and run
**sudo apt-get update** 
This worked for me

**Comment by jedbites** [comment] 2022-10-13 13:34
Hello there! After 2 days of finding a solution. I finally found it! I'm new to this type of thing so I know the struggle and would love to help.

Possible reasons:
*You have security apps like anti-virus active so you need to turn off that for a while. (https://docs.microsoft.com/en-us/windows/wsl/faq#why-do-i-not-have-internet-access-from-wsl)
*DNS Problem (I'll go straight with the permanent solution below.

1. After you turn off any security apps/antivirus/firewall, you can now start step 2 :)
2. cd ~/../../etc (on the ubuntu command line)
3. echo "[network]" | sudo tee wsl.conf (Create wsl.conf file and add the first line).
4. echo "generateResolvConf = false" | sudo tee -a wsl.conf (Append wsl.conf the next line).
5. (Run this on the cmd command prompt) - wsl --terminate Ubuntu
6. (Back to ubuntu commandline) - cd ~/../../etc
7. sudo rm -Rf resolv.conf (Delete the resolv.conf file)
8. (back to cmd command line) - ipconfig /all
9. Find your primary DNS server
10. (back to ubuntu command line) - echo "nameserver X.X.X.X" | sudo tee resolv.conf (Create resolv.conf and append the line.) - Alter X.X.X.X with your primary DNS
11. echo "nameserver 8.8.8.8" | sudo tee -a resolv.conf (Create resolv.conf and append the line.) - 8.8.8.8 is Google's DNS
12. (back to cmd command line) - wsl --terminate Ubuntu
13. Then restart Ubuntu! 


Done! If you thin this is helpful, please do follow my github account. Will help more people with the same struggles I encounter in this learning journey!

**Comment by cokiemon** [comment] 2022-12-16 14:36
Got the same issue today. Only **archive.ubuntu.com** is not reachable. Tried to disconnect company VPN and then it worked.

**Comment by targetdevos** [comment] 2023-01-19 07:04
> sudo apt-get update

Not working your advice....please stop fooling people

**Comment by spelya** [comment] 2023-03-20 19:29
I temporarily disconnected my Bitdefender VPN then  it worked.

Trivial solution, but works perfectly.

**Comment by H1207953831** [comment] 2023-04-29 12:17
> 我暂时断开了我的 Bitdefender VPN 然后它工作了。
> 
> 简单的解决方案，但效果很好。

I never thought there was a problem with the VPN

**Comment by alejocoder** [comment] 2023-06-20 22:09
disable your firewall, i almost punch my pc screen and it was just the firewall from my antivirus

**Comment by JaDaar** [comment] 2023-07-19 20:30
> Try `sudo ping 8.8.8.8` inside your distro (Ubuntu). If you can not reach network, search for network related issues in wsl. If network is reachable it's either dns problem or host being blocked by your network. To check dns try `sudo ping archive.ubuntu.com`.
> 
> If only **archive.ubuntu.com** is not reachable, try changing your apt sources to some other mirror. There is plenty of info on how to do this in the web.

That was the issue for me!  
Luckily I have two internet providers, changing from Xfinity to FioS solved the problem

**Comment by daniel347x** [comment] 2024-03-28 04:36
There have been a lot of intervening comments since https://github.com/MicrosoftDocs/WSL/issues/937#issuecomment-761984062 (posting above with >100 likes) but that posting worked for me - I suggest others scroll up and try it themselves; it's actually easy. Just the one line from that comment is sufficient:

echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null

**Comment by jamous01** [comment] 2024-04-23 15:59
> There have been a lot of intervening comments since https://github.com/MicrosoftDocs/WSL/issues/937#issuecomment-761984062 (posting above with >100 likes) but that posting worked for me - I suggest others scroll up and try it themselves; it's actually easy. Just the one line from that comment is sufficient:
> 
> ```bash
> echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
> ```

You are the best of all, it is exactly like when experts are is talking all noobs must shut up and listen....

**Comment by bkoprivica** [comment] 2024-04-23 22:40
> > There have been a lot of intervening comments since [#937 (comment)](https://github.com/MicrosoftDocs/WSL/issues/937#issuecomment-761984062) (posting above with >100 likes) but that posting worked for me - I suggest others scroll up and try it themselves; it's actually easy. Just the one line from that comment is sufficient:
> > ```shell
> > echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
> > ```
> 
> You are the best of all, it is exactly like when experts are is talking all noobs must shut up and listen....

Is that so, Cracker? You are mistaken. Domain server? Why would one mapper be better than another mapper?

**Comment by mikyll** [comment] 2024-06-04 08:19
In my case the issue was caused by the **Windows mobile hotspot**. By chance I tried **turning it off** and `sudo apt update` went straight.
