### ISSUE TITLE
Instructions need to mentioned that install command requires elevated privleges

### ISSUE THREAD

**Issue by shearichard** [MicrosoftDocs/WSL#1305] opened 2021-10-08 01:56 UTC
In the part of the instructions where the command `wsl --install` the instructions need to make clear that elevated privleges are required for this command to run. Preferably they should include the Powershell equivalent of 'runas' (I'm not a Powershell user so I've no idea what that is).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
* Content Source: [WSL/install.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by SimpleSamples** [comment] 2021-10-31 07:36
It seemed to work for me without elevated privileges so perhaps it would help to specify what the error is that you are getting. The cause might be different.

**Comment by mattwojo** [comment] 2022-02-03 21:53
We state that this install requires admin PowerShell to install:
https://docs.microsoft.com/en-us/windows/wsl/install#:~:text=You%20can%20now%20install%20everything%20you%20need%20to%20run%20Windows%20Subsystem%20for%20Linux%20(WSL)%20by%20entering%20this%20command%20in%20an%20administrator%20PowerShell%20or%20Windows%20Command%20Prompt%20and%20then%20restarting%20your%20machine.

Closing, but if you feel this needs to be stated differently or more clearly, please feel welcome to reopen. Thanks for filing!

**Closed by mattwojo** 2022-02-03 21:53 UTC
