### ISSUE TITLE
The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse. 

### ISSUE THREAD

**Issue by KSam-J** [MicrosoftDocs/WSL#494] opened 2019-09-26 16:28 UTC
I was given this message when attempting to enable WSL 2 with `wsl --set-version Ubuntu 2` :

```
The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse. 
```
This was after running the two `Enable-WindowsOptionalFeature` commands in the previous step, and a reboot.
If it matters, I have also been using WSL 1 with Ubuntu for a couple years now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Biswa96** [comment] 2019-09-26 17:03
Duplicate of this issue https://github.com/microsoft/WSL/issues/4103.

**Comment by craigloewen-msft** [comment] 2019-09-26 17:46
Hi @KSam-J , @Biswa96 is correct this seems to be a duplicate issue. I'd recommend that you follow that issue thread on the main WSL repo for updates. I'll close this issue out since it's already being tracked on the WSL repo.

As well, what build of Windows are you running? You can find it by opening up CMD and running the `ver` command.

**Closed by craigloewen-msft** 2019-09-26 17:46 UTC
