### ISSUE TITLE
how to move the vhdx of wsl2 to other disk

### ISSUE THREAD

**Issue by gao4263** [MicrosoftDocs/WSL#412] opened 2019-06-13 14:10 UTC
I install  wsl2 , i learn that wsl2 use vhdx as store file,  because C disk  is small, so I want to move  the vhdx file  to other disk.

please tell me how to do it. thx

**Comment by mscraigloewen** [comment] 2019-06-13 23:23
You can do this using the `wsl --import` feature. Here's an example of me doing this setup.

![image](https://user-images.githubusercontent.com/42221804/59473480-7459ee00-8df7-11e9-9ba2-5faa3189fa88.png)

If you run into any more issues please reopen this issue, but otherwise I believe your question is solved so I'll close this out for you. Thank you!

**Closed by mscraigloewen** 2019-06-13 23:23 UTC

**Comment by s-usr** [comment] 2019-08-27 22:13
You exported Alpine2 but imported Alpine3. Could you please clarify?

**Comment by s-usr** [comment] 2019-08-28 10:10
Thanks. It will be nice if we could keep the name as is, because this is not a filename; it is a distribution name.

**Comment by s-usr** [comment] 2019-08-28 15:59
Hello... I got "Access is denied" on import. I checked the "Security" for the 'source' and 'destination'. I have administrator priviliges. There should be a trick to handle this. Please advise if you came across this error. Thanks.

**Comment by s-usr** [comment] 2019-09-09 22:46
See https://github.com/microsoft/WSL/issues/4451 as an update.

**Comment by Mrcooder** [comment] 2019-10-15 15:08
@craigloewen-msft I has compeletely followed the way you provide however it seems i lost personal files in my WSL2 distro. Is it a expected behavior or just a bug? :(

**Comment by Mrcooder** [comment] 2019-10-15 15:13
> @craigloewen-msft I have compeletely follow the way you provide, however it seems i lost personal files in my WSL2 distro. Is it a expected behavior or just a bug? :(

I'm sorry, the distro's default user was changed to root, may i bring it back to old user?

**Comment by craigloewen-msft** [comment] 2019-10-15 18:08
@Mrcooder yes there is a way to do this in newer builds. What version of Windows are you using? If you're on the Windows Insiders fast ring then you should have access to this feature as we added it in Build 18980. You can find the details [here](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18980).

**Comment by chiqui3d** [comment] 2020-01-14 01:50
Hello @craigloewen-msft , there is already a way to install Ubuntu distro or any other distro directly on another hard disk, and I have to follow the `import` method?

**Comment by craigloewen-msft** [comment] 2020-01-14 19:45
Easiest way to do it right now is using the import method. Adding the ability to install to another drive, or move to another drive is something we're tracking here: https://github.com/microsoft/WSL/issues/449

**Comment by chiqui3d** [comment] 2020-01-15 00:20
Thank you, but call me a fool. Because once exported, I don't know what to do anymore.

I checked the wsl -l -v versions and now I have 2:
```
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         2
  Ubuntu18        Stopped         2
```

So I have unregister the previous version (Ubuntu-18.04) with  
`wsl --unregister Ubuntu-18.04`

Now what do I have to do?

I've tried this

`wsl.exe --distribution Ubuntu18`

but I get the message:

`The process does not have access to the file because it is being used by another process.
`
If I search for `Ubuntu `in Start Menu and run it, it reinstalls the version I have uninstalled.

So I don't understand very well, can you help me?

**Comment by chiqui3d** [comment] 2020-01-15 01:01
Okay, I just rebooted Windows, and now I can get in. I had to install Windows Terminal(Preview) to be able to enter the distro more easily.

**Comment by craigloewen-msft** [comment] 2020-01-15 19:35
Yes you can run `wsl -d Ubuntu18` to boot into it directly, or run `wsl -s Ubuntu18` to set it to your default distro and then after that just `wsl` will launch you into it. 

Glad that terminal resolved your probelm!

**Comment by mxplusb** [comment] 2020-01-18 17:55
Here is exactly what I did on 19035.1 and it worked without a reboot or errors.

1. Run `powershell.exe` as Administrator

```powershell
PS C:\WINDOWS\system32> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)

# mkdir S:\ISOs\

PS C:\WINDOWS\system32> wsl --export Ubuntu S:\ISOs\ubuntu-wsl.tar

# mkdir w:\VMs

PS C:\WINDOWS\system32> cd w:\VMs
PS W:\VMs> mkdir ubuntu-wsl
PS W:\VMs> wsl --unregister Ubuntu
Unregistering...
PS W:\VMs> wsl --import Ubuntu W:\VMs\ubuntu-wsl S:\ISOs\ubuntu-wsl.tar
PS W:\VMs> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
```

**Comment by pxlrbt** [comment] 2020-03-20 15:13
If anybody is interested: I wrote a little bash and batch script for automating these steps.
https://github.com/pxlrbt/move-wsl

**Comment by Biswa96** [comment] 2020-03-20 15:32
If allowed, you can do it with just one `reg add` command.

**Comment by Neurrone** [comment] 2020-05-15 17:34
The instructions that @mxplusb worked really well for me, thanks!

I had to add a `wsl --shutdown` step before doing the import else it returned an error message saying that the operation timed out because the VM isn't responding. Hoping this gets included in the docs since this is extremely useful for SSDs especially.

**Comment by Lajovic** [comment] 2020-08-26 12:04
I saw a lot of scary answers with many steps and possible errors here, **so I decided to just cut and paste** the folder to a bigger HD.

Then I told windows to link both of the folders:
`mklink /J C:\...\OldFolderName G:\...\GrowAllYouWantHereFolder`

The second folder can have any name. No errors. No reboot. My SSD can breath again.

Btw, don't use powershell, use cmd or this one.

**Comment by rekaerst** [comment] 2020-09-01 04:38
wsl --import --export command made a lot of disk io, can I just modify the registry of lxss?
I changed the registry key at 
```
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{your linux uuid}\BasePath 
```
from default to \\?\D:\Path\to\ext4.chdx and it seems work well.

**Comment by minlare** [comment] 2020-10-09 13:39
A combination of @mxplusb and @Neurrone comments were the solution for me. Thanks

**Comment by banyh** [comment] 2020-10-14 04:04
My steps is a combination of @rekaerst, @Neurrone, and @mxplusb 

1. Backup current vhdx file
    from `%LOCALAPPDATA%\Packages\<PackageFamilyName>\LocalState\ext4.vhdx`
    to `D:\ext4.vhdx`
    (**Most important step. If you can't find correct vhdx file, you shouldn't go ahead**)
2. Remove current distro, like `wsl --unregister Ubuntu-20.04`
3. Reinstall distro from Microsoft Store
4. Export and import
    `wsl --export Ubuntu-20.04 D:\wsl.tar`
    `wsl --unregister Ubuntu-20.04`
    `wsl --import Ubuntu-20.04 D:\Ubuntu-20.04 D:\wsl.tar`
5. Overwrite original vhdx file
    `copy D:\ext4.vhdx D:\Ubuntu-20.04\ext4.vhdx`
6. Set default user
    `ubuntu2004.exe config --default-user <username>`

**Comment by Anutrix** [comment] 2020-11-08 07:33
@banyh Any side effects or do you lose any data?
I wanna try doing it

**Comment by sheep94lion** [comment] 2020-12-02 02:14
> Thanks. It will be nice if we could keep the name as is, because this is not a filename; it is a distribution name.

You can unregister the original distribution before import.

`wsl --unregister Ubuntu-18.04`

**Comment by viraj-shah18** [comment] 2021-01-29 19:06
Hello all, I tried this. Although this worked perfectly fine, I am unable to locate my files present there. Have they been deleted?

**Comment by iegorval** [comment] 2021-02-25 13:50
> My steps is a combination of @rekaerst, @Neurrone, and @mxplusb
> 
> 1. Backup current vhdx file
>    from `%LOCALAPPDATA%\Packages\<PackageFamilyName>\LocalState\ext4.vhdx`
>    to `D:\ext4.vhdx`
>    (**Most important step. If you can't find correct vhdx file, you shouldn't go ahead**)
> 2. Remove current distro, like `wsl --unregister Ubuntu-20.04`
> 3. Reinstall distro from Microsoft Store
> 4. Export and import
>    `wsl --export Ubuntu-20.04 D:\wsl.tar`
>    `wsl --unregister Ubuntu-20.04`
>    `wsl --import Ubuntu-20.04 D:\Ubuntu-20.04 D:\wsl.tar`
> 5. Overwrite original vhdx file
>    `copy D:\ext4.vhdx D:\Ubuntu-20.04\ext4.vhdx`
> 6. Set default user
>    `ubuntu2004.exe config --default-user <username>`

I have tried to follow these steps, but I got `Error: 0x80070057 The parameter is incorrect.` error on the last instruction. I am not very familiar with Windows or WSL2. Maybe you know what might be causing the error, and how to correct it? I am unable to link my subsystem to the original vhdx file even on the drive where it was originally located, unfortunately.

**Comment by rekaerst** [comment] 2021-02-25 14:21
@iegorval Try checking file permission of ext4.vhdx in case you run those commands as the superuser. Also, don't forget to try to turn it on and off again.

**Comment by sonook** [comment] 2021-04-29 04:02
Hi All,

I have found different approach for this problem for moving existing installation to different drive.

Shutdown all VMs by following command
Run command: wsl --shutdown

Go to Registry Path for WSL2 installation.

Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\

Find your installation folder and change the basepath to desired drive and path.

Cut and Paste your ext4.vhdx from default path to desired drive.

Video representation of solution for movement of ext4.vhdx file to other location.

https://youtu.be/ON_dPAO4KZs

**Comment by chdelacr** [comment] 2021-10-05 19:39
> If anybody is interested: I wrote a little bash and batch script for automating these steps. https://github.com/pxlrbt/move-wsl

This is very helpful. However, I'm getting NTFS related errors for unsupported characters, even when the VHDX file is an ext4. Is anyone else experiencing this issue?

**Comment by deekshithanand** [comment] 2021-12-06 20:07
Not Really sure if this is the proper solution. But for anyone looking, simply move it to another drive and not really care about the directories, I tried moving the ubuntu app(simply select move and chane the location ) in Windows App settings. It sort of worked and my ext4.vhd file got moved from C to D:/ drive ! (Correct me if am doing wrong!)

**Comment by YouveGotMeowxy** [comment] 2022-01-20 16:25
Does the `--import` command delete the .tar file after it successfully does the import?

**Comment by Biswa96** [comment] 2022-01-20 16:28
Nope. At least it did not in my case 😜

**Comment by kolodi** [comment] 2022-03-21 14:57
> Hi All,
> 
> I have found different approach for this problem for moving existing installation to different drive.
> 
> Shutdown all VMs by following command Run command: wsl --shutdown
> 
> Go to : regedit
> 
> Go to Registry Path for WSL2 installation.
> 
> Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\
> 
> Find your installation folder and change the basepath to desired drive and path.
> 
> Cut and Paste your ext4.vhdx from default path to desired drive.
> 
> Video representation of solution for movement of ext4.vhdx file to other location.
> 
> https://youtu.be/ON_dPAO4KZs

This has worked perfectly for me. So I guess the export import is not required. Or is there some other considerations in this regard?

**Comment by chdelacr** [comment] 2022-03-21 19:52
> > Hi All,
> > I have found different approach for this problem for moving existing installation to different drive.
> > Shutdown all VMs by following command Run command: wsl --shutdown
> > Go to : regedit
> > Go to Registry Path for WSL2 installation.
> > Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\
> > Find your installation folder and change the basepath to desired drive and path.
> > Cut and Paste your ext4.vhdx from default path to desired drive.
> > Video representation of solution for movement of ext4.vhdx file to other location.
> > https://youtu.be/ON_dPAO4KZs
> 
> This has worked perfectly for me. So I guess the export import is not required. Or is there some other considerations in this regard?

I only would like to know if it is possible to perform this for an ext4 pen drive, or if it is exclusive for NTFS drives.

**Comment by raycheung** [comment] 2022-04-02 10:12
> Hi All,
> 
> I have found different approach for this problem for moving existing installation to different drive.
> 
> Shutdown all VMs by following command Run command: wsl --shutdown
> 
> Go to : regedit
> 
> Go to Registry Path for WSL2 installation.
> 
> Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\
> 
> Find your installation folder and change the basepath to desired drive and path.
> 
> Cut and Paste your ext4.vhdx from default path to desired drive.
> 
> Video representation of solution for movement of ext4.vhdx file to other location.
> 
> https://youtu.be/ON_dPAO4KZs

This helped me out! Thank you so much!

**Comment by Jammrock** [comment] 2022-04-18 21:15
I wrote some PowerShell automation for @sonook's registry-based WSL2 disk move.

https://github.com/Jammrock/Move-WSL2NewDrive

Tested locally on Win11 using PowerShell 7. YMMV on Win10 and/or Windows PowerShell 5.1.

**Comment by arnavmehta7** [comment] 2022-10-08 09:47
> Nope. At least it did not in my case 😜

Hey, can you please tell me if I can delete mine tar file, Almost 60 gb has been freedup from my main drive. Can I now delete the .tar file after importing?

**Comment by vle003** [comment] 2022-11-04 09:36
> 
> Hey, can you please tell me if I can delete mine tar file, Almost 60 gb has been freedup from my main drive. Can I now delete the .tar file after importing?

Sure, you can.

**Comment by vle003** [comment] 2022-11-04 09:38
It's could be better if we can specify the path to store disk image when install WSL. The registry mod work well but you need to touch it everytime you install a new distro.

**Comment by jywangx** [comment] 2023-12-19 16:57
> wsl --shutdown

Thanks

**Comment by WangFengtu1996** [comment] 2024-01-26 09:10
create `mklink`  using  `cmd.exe` for `ext4.vhdx`

**Comment by afifurrohman-id** [comment] 2024-01-30 12:10
> Hi All,
> 
> I have found different approach for this problem for moving existing installation to different drive.
> 
> Shutdown all VMs by following command Run command: wsl --shutdown
> 
> Go to : regedit
> 
> Go to Registry Path for WSL2 installation.
> 
> Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\
> 
> Find your installation folder and change the basepath to desired drive and path.
> 
> Cut and Paste your ext4.vhdx from default path to desired drive.
> 
> Video representation of solution for movement of ext4.vhdx file to other location.
> 
> https://youtu.be/ON_dPAO4KZs

**Testing on Windows Current 11, This is most simple way without needing to change config and default user.**

**Comment by AuroraMaster** [comment] 2024-08-24 22:55
What should I do if the registry is lost? I only have VHDX and exe files, and I have customized a rag.
`Windows Registry Editor Version 5.00

```
[HKEY_USERS\S-1-5-21-2094937328-1482775198-4211468522-500\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{0bcb98b4-3ac6-457d-b574-1a61ceeb0d2c}]
"State"=dword:00000001
"DistributionName"="Debian"
"Version"=dword:00000002
"BasePath"="\\\\?\\F:\\Debian"
"Flags"=dword:0000000f
"DefaultUid"=dword:00000000
```

But it prompts an error

```
<3>WSL (14) ERROR: CreateProcessParseCommon:757: getpwuid(0) failed 2
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\VMware\bin\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate c:\Users\Administrator\AppData\Local\Programs\cursor\resources\app\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate c:\Users\Administrator\AppData\Local\Programs\cursor\resources\app\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate c:\Users\Administrator\AppData\Local\Programs\cursor\resources\app\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Python311\Scripts\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Python311\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\veighna_studio\Scripts\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\veighna_studio\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Python39\Scripts\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Python39\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files (x86)\Common Files\Oracle\Java\javapath
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Windows\system32
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Windows
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Windows\System32\Wbem
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Windows\System32\WindowsPowerShell\v1.0\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Windows\System32\OpenSSH\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Common Files\Autodesk Shared\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\dotnet\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\MT
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft SQL Server\120\DTS\Binn\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files (x86)\Wolfram Research\WolframScript\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\WINDOWS\sys
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\JBIDE\shell
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\PowerShell\7\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\nvm
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\nodejs
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\Git\cmd
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\Huawei\ohpm-repo\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Administrator\.bun\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\doxygen\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\Graphviz\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\ffmpeg\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate G:\PostgreSQL\16\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\7-Zip
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\Rust\.cargo\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Administrator\scoop\shims
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\JetBrains\IntelliJ IDEA 2020.1\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\JetBrains\GoLand 2020.1\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\JetBrains\PyCharm Professional Edition with Anaconda plugin 2020.1\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\Fiddler
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Administrator\go\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Azure Data Studio\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Bandizip\
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\nvm
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\nodejs
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate F:\Debian
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\Microsoft VS Code\bin
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Administrator\AppData\Local\JetBrains\Toolbox\scripts
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\JBIDE\shell
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\nvm
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate D:\nodejs
<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\Administrator\.bun\bin
Processing fstab with mount -a failed.
Failed to mount C:\, see dmesg for more details.
Failed to mount D:\, see dmesg for more details.
Failed to mount E:\, see dmesg for more details.
Failed to mount F:\, see dmesg for more details.
Failed to mount H:\, see dmesg for more details.
Failed to mount I:\, see dmesg for more details.

<3>WSL (14) ERROR: CreateProcessEntryCommon:334: getpwuid(0) failed 2
<3>WSL (14) ERROR: CreateProcessEntryCommon:505: execvpe /bin/sh failed 2
<3>WSL (14) ERROR: CreateProcessEntryCommon:508: Create process not expected to return

[已退出进程，代码为 1 (0x00000001)]
```
`<3>WSL (14) ERROR: UtilTranslatePathList:2866: Failed to translate`

These are all valid environment paths
Suspect uid is wrong。

How to find or restore the correct   `DefaultUid`

**Comment by crramirez** [comment] 2024-08-24 23:51
Short answer:

`wsl --import-in-place <new_distro_name> <path_to_vhdx>`
