### ISSUE TITLE
WSL install, wsl.exe --install not running.

### ISSUE THREAD

**Issue by jallafish** [MicrosoftDocs/WSL#1100] opened 2021-02-19 11:27 UTC
The command for Linux install, `wsl.exe --install` is not running the install (with OS build 20262 or higher).

You need to specify the Linux distribution. For Ubuntu; `wsl.exe --install -d Ubuntu`

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/nb-no/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by chk1** [comment] 2021-09-29 17:07
Same issue on this page: https://docs.microsoft.com/en-us/windows/wsl/setup/environment#install-wsl

> The --install command performs the following actions:
> [...]
> * Downloads and installs the Ubuntu Linux distribution (reboot may be required)

Ubuntu was not installed after I ran the `wsl --install` command, using Windows 10 x64 20H2.

**Comment by slonopotamus** [comment] 2022-01-12 20:31
Please, close this as a duplicate of #1303 that has analysis on why and when `wsl --install` doesn't work.

**Closed** 2022-03-03 21:43 UTC
