### ISSUE TITLE
it's sdb not sbd  .... page had incorrect information

### ISSUE THREAD

**Issue by robertnormanhiggins** [MicrosoftDocs/WSL#1339] opened 2021-11-03 09:23 UTC
[Enter feedback here]
The page refers to /dev/sbd  ... it should refer to /dev/sdX where X is a, b, c, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c96a605e-9f3c-41b4-b964-412572fccd41
* Version Independent ID: 6734e772-029a-9d2c-fef7-435faf8e0cac
* Content: [Expand the size of your WSL 2 Virtual Hard Disk](https://docs.microsoft.com/en-us/windows/wsl/vhd-size)
* Content Source: [WSL/vhd-size.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/vhd-size.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment] 2021-11-12 19:32
Fixed. Duplicate of https://github.com/MicrosoftDocs/WSL/issues/1351
Thank you!

**Closed by mattwojo** 2021-11-12 19:32 UTC
