### ISSUE TITLE
Can't access applications running on Windows localhost From WSL using nameserver IP

### ISSUE THREAD

**Issue by endeesa** [MicrosoftDocs/WSL#1328] opened 2021-10-21 15:29 UTC
- The only way I can access a windows web app, is if I bind to 0.0.0.0., and use the LAN IP address
- The nameserver IP address doesn't seem to work

WSL info:
  "platform": {
    "Linux", 
    "MYUSERNAME", 
    "5.4.72-microsoft-standard-WSL2", 
    "#1 SMP Wed Oct 28 23:40:43 UTC 2020", 
    "x86_64"
}

OS: {  Windows 10 Pro,  19042.985 }

![wsek_net_issue](https://user-images.githubusercontent.com/14007831/138309720-7e9bcd80-8294-45d8-98cd-dfa214a757ca.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5f3211d-52bd-3566-874a-5c78cb01ddd0
* Version Independent ID: f9e21bfa-6316-7d45-3b34-834a78bcaf0f
* Content: [Accessing network applications with WSL](https://docs.microsoft.com/en-us/windows/wsl/networking)
* Content Source: [WSL/networking.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/networking.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment] 2021-11-11 21:25
This is expected, you would need to access your Windows server the same way you would access it from a different machine on the same network. I'll close this out as by design, if you have more questions please feel free to comment more :)

**Closed by craigloewen-msft** 2021-11-11 21:25 UTC

**Comment by dmothes** [comment] 2023-04-11 09:18
Hi, I tried this out on my company laptop, but this is not working. Can I see somewhere that this access to ports is blocked from the firewall? I can't see something inside windows firewall. BR.
