### ISSUE TITLE
WSL2 Support for Windows Server 2019

### ISSUE THREAD

**Issue by kamalmaheshwari** [MicrosoftDocs/WSL#678] opened 2020-05-13 11:39 UTC
What's the plan to support WSL2 on Windows Server 2019? We are eagerly waiting to run Linux containers on Windows Server 2019 platform

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233355e5-2fe3-a827-a1bf-ef1ae3ee5f36
* Version Independent ID: 991e4422-12dc-68a6-21a6-9741710fd47a
* Content: [WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-index#feedback)
* Content Source: [WSL/wsl2-index.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-index.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by TBBle** [comment] 2020-06-20 06:55
Since WSL2 was introduced well after Windows Server 2019, I cannot see that it would be backported to an LTSC version. I haven't confirmed this, but the Windows Server, version 2004 SAC release should have WSL2 support. As far as I can tell though, the [Windows Server, version 2004 SAC release notes](https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-2004) are focused on the container image release, even though ISO releases and cloud provider VMs have been appearing since May.

**Comment by chara1ampos** [comment] 2020-09-01 18:44
@TBBle the 2004 version has no desktop support. Only LTSC versions have desktop support. It is a sad situation that we have to wait until year 2022 or 2025 for a new Windows Server LTS, just to be able to use WSL2, by which time it may well be obsolete. I will have to downdgrade a 28 core workstation to regular Windows 10 just to use WSL2 and CUDA, but then I will lose the ability for multiple users to be logged in. Microsoft needs to do (a lot) better if they want Windows Server to keep up with Linux.

**Comment by TBBle** [comment] 2020-09-02 00:09
@chara1ampos: Given that it's [2-3 years between LTSC releases](https://docs.microsoft.com/en-us/windows-server/get-started-19/servicing-channels-19#long-term-servicing-channel-ltsc), and Windows Server 2019 was based on Windows 10 1809, there is a strong expectation of an LTSC release in 2021.

You could jump forward to the [vNext LTSC preview](https://blogs.windows.com/windows-insider/2020/08/26/announcing-windows-server-vnext-preview-build-20201/), perhaps? Given the timing, this suggests we might get a Windows Server LTSC release paired with Windows 10 21H1, as there's been no indication yet that 21H1 has forked from the ["active development builds"](https://docs.microsoft.com/en-us/windows-insider/flight-hub/).

**Comment by therealdandecker** [comment] 2020-11-24 03:27
I can confirm after testing tonight that even in the preview release of 2004 LTSC with dekstop that WSL2 is not functioning; I did an install with the same setup as on my windows 10 box where I have it running and could not get it to run.

I did read that the linux kernel was not included in the preview releases, but I am unclear as to what that meant, i.e. is it not supported or simply its moved beyond preview releases.

**Comment by TonyTwoStep** [comment] 2020-12-01 01:12
Also can confirm the above. I'm on the latest preview release of Server 2019 (based on 2004) 

The commands 
`wsl --set-default-version 2
or
 wsl --set-version <distro> 2`
just output the help message. 

Docker EE doesn't use WSL2 and when attempting to force it or Docker Desktop to do so it errors out saying it cannot parse the output of the wsl command (which is just the help message). Even tried building the WSL kernel from source and that didn't work...

**Comment by TBBle** [comment] 2020-12-01 06:27
Yeah, it sounds like the `wsl` binary is still from WSL1, if it doens't know the `--set-default-version` message, which suggests the whole subsystem is WSL 1 still.

**Comment by awakecoding** [comment] 2020-12-09 18:45
I would be interested as well, especially if the Linux MongoDB container was work correctly with a docker volume under WSL2. I have a multi-container application using Windows containers on Windows, but there are critical issues that have been known for years that prevent MongoDB (and possibly other databases) from working correctly inside Windows containers. At this point I don't care if we have to use Windows containers or Linux containers, all I really want are containers on Windows Server 2019.

**Comment by therealdandecker** [comment] 2020-12-09 19:04
WSL2 is the only way I think. The windows containers are useful but severely limited in terms of availability compared with Linux. The ability to run Linux containers “natively” in Windows Server to me is critical.

The fact that it is not included in the next LTSC release is very surprising as that means (potentially) it will not be available mainstream until 2024 (assuming same release schedule.)

Best,

Dan Decker
________________________________

**Comment by awakecoding** [comment] 2020-12-09 19:33
@therealdandecker I agree it would definitely be better to have an officially supported option to run Linux containers on the latest LTSC release of Windows Server with a GUI. If WSL2 is added only on the upstream semi-annual channel, it would be very difficult to get customers to use it, as a lot of people still just want Windows Server + GUI and RDP (even though it may seem like a bad thing, it's what a lot of people do).

But realizing that getting Linux containers to run properly (including databases that are very tied to specific filesystem i/o calls) on Windows Server, I would settle for simply using Windows containers on Windows, as this is the only *native* option. However, even Windows containers on Windows suffer from severe limitations and critical issues, so we are stuck with no good option in the end.

WSL2 + proper database support, or Windows containers on Windows with bug fixes for the issues preventing databases from working, but we've got to have at least one of the two and fast. Otherwise, this really means that if you can put up with the long list of limitations that come with Windows containers, you are still stuck without containerized database support, which is ridiculous.

https://github.com/docker-library/mongo/issues/385
https://github.com/microsoft/Windows-Containers/issues/37

**Comment by therealdandecker** [comment] 2020-12-10 14:48
How does support for feature requests like this work? Is it possible to open a ticket while LTSC is still in preview mode? Has it been included in one of the semi-annual release channels and just not here?

I have seen things online but not fully tested WSL2 in SAC.

Best,

Dan Decker
________________________________

**Comment by denfromufa** [comment] 2021-02-02 14:21
@shanselman I really wanted to use WSL2 that you advertised. But there is no VM with Windows Server + WSL2 that I can run with it in the cloud! I guess going back to Linux ¯\_(ツ)_/¯

**Comment by TBBle** [comment] 2021-03-07 03:55
There is a ticket specifically for WSL2 on the now-announced Windows Server LTSC 2022 (late 2021) https://github.com/microsoft/WSL/issues/6301. The current ticket, being a report against _the docs_, is probably not bringing much visibility to a feature request.

The documentation does currently correctly state that you need [a newer build of windows for WSL2 than Windows Server 2019](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-2---check-requirements-for-running-wsl-2), and actually explicitly says "Windows 10" is the requirement; the [Windows Server instructions](https://docs.microsoft.com/en-us/windows/wsl/install-on-server) don't mention WSL2 at all, but no released Windows Server LTSC version has a new enough kernel build for WSL2 anyway.

**Comment by awakecoding** [comment] 2021-03-07 15:16
@TBBle WSL2 + Linux containers on Windows Server appear to be dead in the water, unfortunately. I managed to get a clearer statement answer twitter: https://twitter.com/WSV_GUY/status/1358522964052832257?s=19

So the current thinking is that WSL2 is great as a developer tool on Windows 10, but supporting it officially on Windows Server would give people the wrong idea since they might start using it for production workloads.

The thing is that this is *precisely* what most people waiting for WSL2 on Windows Server want to do it with: run production workloads. I don't see a reason why it would not be possible to make it run unofficially, but it'll always be an unsupported option without Microsoft's stamp of approval.

Unless someone can convince Microsoft otherwise, I think WSL2 will remain a Windows 10 developer toy, unfortunately. It's just very frustrating because WSL2 correctly handles filesystem operations required by databases, so it's almost perfect as-is, if only it could be made official.

**Comment by therealdandecker** [comment] 2021-03-07 15:27
That’s the end of that I guess.

Surprised in a way that the folks there making these decisions do not see WSL2 as a viable path for production workloads when WSL2 is using the Hyper-V framework. I am more surprised I think that it’s framed as a “wholly bad idea” rather than something that Microsoft just does not want to support at this time from a strategic standpoint (production WSL2.)

I would think its a matter of product support / maintenance but there must be other things under the covers they think make it less reliable for production workloads.
________________________________

**Comment by awakecoding** [comment] 2021-03-07 15:43
@therealdandecker there used to be an LCOW effort that didn't really go beyond the experimental stage, so maybe they just decided on never doing it back then. It's sad because WSL2 what the original LCOW should have been, so they now have a good basis to make it work.

The issue here is that even Windows containers on Windows have several unfixed issues, starting with the lack of graceful shutdown support. Most databases either don't have official images (SQL Server 2019! Official Linux containers only) or run into issues that ought to be fixed in Docker for Windows (MongoDB).

From what I can see, they now have their eyes on AKS + Azure Stack HCI, while making some fancy GUIs in Windows Admin Center to "ease using Windows containers". That's not going to work unless they give "simple" containers a lot more love.

I think one of the unspoken reasons for not wanting Linux containers on Windows is because they don't really know how to make this thing integrate well with the Windows security system. It's literally a foreign thing running inside Windows, and how are AVs going to deal with what exactly? And I'm not even talking about how most AVs destroy Docker for Windows by default and barely even have docs on how to make it work correctly.

My guess is they hope most customers would migrate to Kubernetes for their container workloads and simple stick to Windows containers on Windows, and Linux containers on Linux, which means having a pool of Windows and Linux nodes inside a Kubernetes cluster. This is absolutely overkill for 80% of use cases, but that's what seems to be the target right now.

**Comment by TBBle** [comment] 2021-03-07 22:23
As far as I can tell from in-passing GitHub PR discussions with Windows Container Platform team members, LCOW is not dead, and is still being actively supported in hcsshim and containerd by them. Docker are less-supportive: https://github.com/docker/for-win/issues/6470. That doesn't specify what their use-cases are, and LCOW may be considered a developer-only feature as WSL2 apparently is; I've never tried it on Windows Server.

I had hoped that WSL2 would lead to WSL2-based LCOW, particularly since WSL2 is using the same underlying Windows infrastructure as HyperV-isolated containers, and on the Linux side your WSL2 distros _are_ containers, so things would _just work_, but for now I guess Docker Desktop's "Docker-in-Docker" approach for Linux containers in WSL2 is the closest we have.

**Comment by Florian-cypheR** [comment] 2021-03-30 14:03
Hi there. 
I am in trouble because i have established all my development strategy on deploying a web app through a Docker's container installed on a Windows Server 2019. 
To make a long story short : i have spent a long time on trying to make a linux containers (ShinyProxy to be exact) works on WS19 before i found this tread. 

There is any workaround to make docker's Container works on WS19 ?

**Comment by TBBle** [comment] 2021-03-30 23:09
> There is any workaround to make docker's Container works on WS19 ?

As a workaround, try Docker's Hyper-V mode, perhaps.

**Comment by John0King** [comment] 2021-03-31 11:56
I want docker for windows it because it  have a GUI,  and  I just can not believe that we can not use  wsl2+docker with windows server with UI in 2021.3.31.
anything stop you make wsl2  a standalone software instead of  depends on OS depends on OS  depends on OS 

IE  depends on OS , it's die.
Old Edge depends on OS , it's die.
UWP depends on OS, it's dying.
WSL2 depend on OS, it's ~~~~~

what can I say ?    there are reasons that windows server lose the market  for Server OS .

**Comment by Florian-cypheR** [comment] 2021-04-01 15:31
> 
> 
> > There is any workaround to make docker's Container works on WS19 ?
> 
> As a workaround, try Docker's Hyper-V mode, perhaps.

I have trying it on the Windows Admin Center and it doesn't work because a functionnality is not installed. I did the same on PowerShell but the daemon refuse to launch due to unsufficients rights.
I'm sure that Hyper-V and the containers are installed but perhaps i miss something - i'll you tell if i find something later.

Nonetheless : thanks for the help 👍 

But... 
As you guys highlight it : it seems that docker won't work well before the release of the WS2022... in the hypothesis that Microsoft engage itself into WSL2.

Wait and see ? 🤔

**Comment by therealdandecker** [comment] 2021-04-01 17:50
WS2022 does not include WSL2 and does not intend to- folks at Microsoft have previously stated (link somewhere in this thread) that WSL2 is not intended as a production solution.

Docker Desktop runs on windows server and I think it uses a Linux kernel allowing you to run Linux containers because Docker Desktop requires Hyper-V when not using WSL2.

Docker Desktop should work on Windows Server 2019 but it would need to be with the desktop experience (you actually can run some GUI apps on server core but why would you.)

Three options really:

1- docker desktop on windows sever
2- full hyper-v VM running Linux and Docker
3- Windows Containers if you’re running .NET or windows compatible technologies for windows containers


________________________________

**Comment by John0King** [comment] 2021-04-12 11:00
in fact, not every cloud virtual machine support  Hyper-V,  so it even not a option for docker desktop + hyper-V

**Comment by therealdandecker** [comment] 2021-04-12 11:10
Not sure what you are trying to say here, but my point/outlined solutions are the only ways I know for running Linux containers on Windows Server.

Yes, not everything can run Hyper-V
but in that case Docker containers on Windows Server would not work anyway.

The overarching point is that to run Docker/Linux containers some form of virtualization is needed. The native container functionality that can be enabled on windows server is limited to the Windows NT kernel and thus windows server nano images. Even WSL2 if it were available on Windows Server utilizes the Hyper-V framework (so you would need a virtualization-capable machine or VM.)

Best,

Dan Decker
________________________________

**Comment by John0King** [comment] 2021-04-12 11:27
so  wsl2  can not be use in a VM environment that do not support the nest virtualization ?

**Comment by TBBle** [comment] 2021-04-12 13:07
I'm fairly sure LCOW works without virtualisation, although it doesn't work in many other important ways, so it's usage is very limited.

**Comment by matsmcp** [comment] 2021-04-15 09:06
Another vote for WSL2 on 2019/2022. 
We need a WSL subsystem on a supported server with a GUI and a decent lifecycle.
And since there is a huge difference in the level of functionality between WSL1 and 2 the later is the preferred

**Comment by matsmcp** [comment] 2021-04-15 09:19
Also https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq should be updated.
The statement "WSL 2 is available on all SKUs where WSL is currently available, including Windows 10 Home." should be changed so it is made clear that it only applies to Win 10 Sku:s, not server SKU:s

**Comment by therealdandecker** [comment] 2021-04-15 11:35
I think unfortunately it’s not happening. This link was shared earlier in the thread by Marc-André Moreau.

Basically it’s a response from someone at Microsoft indicating WSL2 is not intended for production use and thus is excluded from Windows Server.

Their comments depict it very much as a dev tool to work on Windows and deploy on Linux servers/containers without a lot of hassle.

https://mobile.twitter.com/wsv_guy/status/1358522964052832257?prefetchTimestamp=1618486194412

Best,

Dan Decker
________________________________

**Comment by diplopito** [comment] 2021-04-30 12:44
What about this: https://www.thomasmaurer.ch/2019/08/how-to-install-wsl-2-on-windows-server/ ?

**Comment by therealdandecker** [comment] 2021-04-30 12:55
Tried it. Didn’t work for me.

Best,

Dan Decker
________________________________

**Comment by diplopito** [comment] 2021-04-30 22:53
Unfortunately for me neither. As mentioned on this thread, must have been dropped for security and performance reasons.

**Comment by romerod** [comment] 2021-05-04 06:19
What about this?

https://docs.microsoft.com/en-us/windows/wsl/install-on-server

Is it V1? Documentation is really confusing

**Comment by TBBle** [comment] 2021-05-04 08:51
That's correct, the Windows Server instructions only cover WSL, as they predate WSL2 and have not been updated to cover WSL2. I'm not even sure if WSL2 works on Windows Server SAC releases. I assume it did, since it was working on LTSC up until recently.

The TOC just says "Install WSL & update to WSL 2", but [the page with the WSL2 instructions](https://docs.microsoft.com/en-us/windows/wsl/install-win10) is titled "Windows Subsystem for Linux Installation Guide for Windows 10".

So you're also correct, the documentation is confusing. ^_^

**Comment by therealdandecker** [comment] 2021-05-04 09:47
WSL2 does not to my knowledge work on LTSC Server 2019 or latest 2022 builds and (weirdly) is not intended to.

I understand how it ended up there but seems strange to simultaneously hype how WSL2 is an incredible innovation but not production ready.
________________________________

**Comment by diplopito** [comment] 2021-05-04 09:57
I use it as a developer and can test simultaneusly on Ubuntu 16.04, 18.04 and 20.04, works perfect. But from a security perspective, it is a bit scary that you can have access to all your Windows partitions and do with the files whatever you want.

**Comment by milkshakeuk** [comment] 2021-07-23 09:50
We use Windows Server 2019 as teamcity build agents and want to use docker in teamcity with support for linux containers and now it sounds like this is not going to happen and that we need a linux based build agent? pfff, I understand that they dont want to  use WSL2 for production hosting but as a CI/CD tool? did they not think about this workload?

**Comment by ReFleXzZ** [comment] 2021-12-31 05:24
This is very sad, since I need WSL2 running on my Windows Server 2022 Datacenter.. It's really unfortunate, since most containers I need, won't run on wsl1. And Hyper-V does indeed use a higher workload and is much slower in it's reaction times to user input. Really frustrating, that it's still not a thing in the 2022 Server.

To be honest I never liked Windows that much, but I thought that Windows Server 2022 would indeed be used a lot more than before, since cloud computing + virtualization have become a really big thing and all these new features were implemented. I suggest Microsoft implements WSL2 for at least Windows Server 2022 or Microsoft will loose much important companies, since it's more hasslefree to deploy containers on linux than it is on Windows. The same counts for Kuberenetes in my opinion.

**Comment by BradleyDS2** [comment] 2021-12-31 05:45
Thanks a lot Microsoft, we've just migrated away from Server 2019 Datacenter Edition.

**Comment by ordersinrandom** [comment] 2022-01-14 17:06
Nowadays most of the new server side programs are containerized, in docker, and run with k8s. This is by default how many of the development team works except those with legacy technology that cannot be packed. That means in many cases those containers simply CANNOT be deployed on windows server in any production sense. Naturally people just moves away from windows server just because of this.

**Comment by craigloewen-msft** [comment] 2022-01-28 19:08
Hi folks, I've made a statement on the microsoft/wsl GitHub repo to help clarify this. I'll reproduce it here:

```
Hi folks! We've listened to feedback in this area and I'd like to clarify that WSL 2 distros are now supported on Windows server versions 2004 and 20H2. This means that you can run WSL 2 distros on those Server versions. Currently WSL 2 distro support is not on Windows Server 2022, but we are investigating this. If you'd like to use WSL 2 distros on Windows Server I would recommend you use Windows server version 20H2 for the time being. Thank you all for giving us your feedback here, I look forwards to hearing more as we give more updates when they're available.
```
https://github.com/microsoft/WSL/issues/6301#issuecomment-1024521788

Please follow [this thread on the WSL GitHub repo](https://github.com/microsoft/WSL/issues/6301#issuecomment-1024521788) for further updates on WSL and Windows Server. (I'll be closing this one out for house keeping purposes)

**Closed by craigloewen-msft** 2022-01-28 19:08 UTC

**Comment by craigloewen-msft** [comment] 2022-05-24 21:35
WSL 2 distros are now enabled on Windows Server 2022, you can get access to it right away by installing a KB. You can read more at this comment: 

https://github.com/microsoft/WSL/issues/6301#issuecomment-1136453235

**Comment by butkandrius** [comment] 2022-06-20 18:30
Hi, I read lots of comments, so is no way how to start linux containers on Windows Server 2019? Windows containers are working fine but when I switch to linux containers and try to run them I am getting this error
`failed to start service utility VM (createreadwrite): hcsshim::CreateComputeSystem feed74e37d12e5f46740b066cb1d49fca497ebad70755bcd8586d26f43ff74ce_svm: The virtual machine could not be started because a required feature is not installed `. Even though hyper-V is enabled and all the system requirements met.

**Comment by TBBle** [comment] 2022-06-21 07:33
You may still be able to run containers user the Docker Desktop Hyper-V backend, although Docker Desktop does not formally support Windows Server, as far as I recall.

You should also be able to use LCOW (v1)-based containers, but [Docker has deprecated support for that and will drop it in the next major release](https://github.com/docker/cli/blob/master/docs/deprecated.md#linux-containers-on-windows-lcow-experimental), and [Microsoft also considers it deprecated](https://docs.microsoft.com/en-us/troubleshoot/windows-server/containers/support-for-windows-containers-docker-on-premises-scenarios#supported-configurations-for-container-hosts). Although the error message you got suggests that you got past that point, and are hitting a lower-level issue. That said, LCOW was never very _good_, it had a lot of limitations that were never resolved, which is why everyone has deprecated it in favour of future containerd-based approaches which are currently (AFAIK) still WIP.

**Comment by TBBle** [comment] 2022-06-22 06:59
As far as I can see in the release notes, Docker Desktop has most-recently deprecated Windows 1709 (build 16299). They only formally support Windows 10 versions still in servicing, so https://docs.docker.com/desktop/windows/install/ lists Windows 10 21H1 or higher (20H2 for Enterprise/Education) but even if they are enforcing that in the installer, an installer from early-mid 2021 (when [the 30-month support window for Windows 10 version 1809 expired](https://blogs.windows.com/windowsexperience/2018/11/13/resuming-the-rollout-of-the-windows-10-october-2018-update/)) would still allow installation. Certainly the underlying Docker Engine still supports Windows Server 2019; the upcoming Docker Engine 22.06 release lifts the minimum Windows version _to_ Windows Server 2019.

Windows 10 Enterprise 2019 LTSC is still in Mainstream support [until January 2024](https://docs.microsoft.com/en-us/lifecycle/products/windows-10-enterprise-ltsc-2019), but I assume Docker Desktop isn't consideration the LTSC versions of Windows 10, since they're intended for specialised devices.

**Comment by olsonperrensen** [comment] 2022-09-25 18:23
Still no support for build 17763 (LTSC 2019) after two years and four months.

**Comment by TBBle** [comment] 2022-09-26 00:23
I don't think there's any reason to expect WSL2 to start working on LTSC2019, since it also was never working on the Windows 10 version of that same kernel, so it's quite possible that the Windows kernel-level support needed for WSL2 was simply not present until 19041 (20H1).

Windows Server _LTSC_ 2019's OS-level feature set was basically fixed at release in 2018.
