### ISSUE TITLE
Error - The referenced assembly could not be found

### ISSUE THREAD

**Issue by ChandanKSahu** [MicrosoftDocs/WSL#368] opened 2019-03-09 09:51 UTC
I face the following error in powershell.
Enable-WindowsOptionalFeature : The referenced assembly could not be found.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

If I try to enable the windows feature 'Windows Subsystem for Linux' from control panel, I get the error code 0x80073701. And it redirects me to the page https://support.microsoft.com/en-us/help/2734782/net-framework-3-5-installation-error-0x800f0906-0x800f081f-0x800f0907, which is of no help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by dnight71** [comment] 2019-03-20 00:38
Same exact issue here. Any luck?

**Comment by RRMgit86** [comment] 2019-03-20 01:35
Been having the same issue, any suggestions?

**Comment by rm-rf-home** [comment] 2019-03-21 13:54
Same when trying to disable the Linux Subsystem feature
![image](https://user-images.githubusercontent.com/36776420/54756795-39c22a00-4be9-11e9-94bb-bfcd6356c2e7.png)

**Comment by opeerator** [comment] 2019-04-12 14:36
Any ideas?

**Comment by mjd2012gdg** [comment] 2019-04-15 19:21
I have the same issue. I assumed it was my company windows admins being evil again, but sounds more like a bug now...

**Comment by opeerator** [comment] 2019-04-16 15:05
I've heard the only way to fix this is to update to 1809 but still I'm not sure that it would be effective or not?!

**Comment by Keeeweee** [comment] 2019-04-24 07:59
> I've heard the only way to fix this is to update to 1809 but still I'm not sure that it would be effective or not?!

I'm already at 1809 and having the exact same issue as @mjd2012gdg

**Comment by opeerator** [comment] 2019-04-24 09:32
> > I've heard the only way to fix this is to update to 1809 but still I'm not sure that it would be effective or not?!
> 
> I'm already at 1809 and having the exact same issue as @mjd2012gdg

Actually I have updated to 1809 and it is working fine now.

**Comment by lailabeauty** [comment] 2019-05-08 19:46
sorry, I have the same issue

**Comment by roemhildtg** [comment] 2019-05-31 22:18
Same issue.

**Comment by tht13** [comment] 2019-06-04 07:02
Same issue here

**Comment by raviv** [comment] 2019-06-04 12:51
Same here :(

**Comment by rok-povsic** [comment] 2019-06-06 04:59
Same here.

**Comment by mjd2012gdg** [comment] 2019-06-06 15:12
@taraj mind replying, or is this just another Microsoft dropped ball?

**Comment by mscraigloewen** [comment] 2019-06-06 16:10
Hi there! We're looking into this issue internally, in the meantime please try running this command in a command prompt Window with administrator privileges:

`DISM /Online /Cleanup-Image /CheckHealth`

It may fix your problem while we continue troubleshooting. Thank you all for your patience! 😊

**Comment by mscraigloewen** [comment] 2019-06-06 16:49
Could you help us troubleshoot by sending us your log files?

If you're still experiencing this issue please:
* Take all of the log files under: 
`C:\windows\logs\cbs\` 
And the file: `C:\Windows\Servicing\sessions\sessions.xml`
* Place them into a zip
* And send them to my email: `crloewen@microsoft.com`

**Comment by xZero707** [comment] 2019-06-15 13:49
So no solution still? Seriously, issue was reported in March.

You recommended DISM command but I'm running newly installed Windows. I will try running the command anyway.

**Comment by mjd2012gdg** [comment] 2019-06-17 15:47
Microsoft is actively investigating the issue.  They have been working with me for the last two weeks to find a fix.  Once they have a working fix, I'm sure it will be announced here.

IMHO: It seems to be a corrupted patch caused possibly by a subsequent patch.  If you can't wait, you might try doing a fresh install of Windows 10 with NO patches and once the Linux sub system is installed then do your patching.

**Comment by mjd2012gdg** [comment] 2019-06-18 19:35
Update:  Microsoft was able to resolve my issues.  I'm sure they will post the instructions soon.

**Comment by artur-sim** [comment] 2019-06-24 14:19
Where they will post how to solve this issue ?

**Comment by mjd2012gdg** [comment] 2019-06-24 19:07
@mscraigloewen any idea how soon you will have the official how-to available?

**Comment by rok-povsic** [comment] 2019-06-24 19:22
I've managed to solve the issue by upgrading to the latest Windows 10 version (which is, at this point, 18362.175).

**Comment by mscraigloewen** [comment] 2019-06-24 20:51
Once we develop a general solution we'll post it here in this thread. This issue is happening because the optional component has gotten into a bad state. This can happen for a variety of reasons, and so the troubleshooting can often be specific, and therefore hard to generalize. We're working on getting a generalized solution!

**Comment by AliAlfaryhin** [comment] 2019-07-09 14:42
Any updates on this issue?

**Comment by mscraigloewen** [comment] 2019-07-09 20:05
We're still working on getting a generalized solution. Thank you for your patience, I know dealing with an error like this can be frustrating but we are still working on it, and I'll post any updates on the issue to this thread.

**Comment by NiveditJain** [comment] 2019-07-10 09:38
I am still getting the same issue

**Comment by APigg0070** [comment] 2019-08-06 03:02
I was having this issue until I installed Windows version 1903 (I previously had version 1803). I had to go download it manually since my computer didn't find the most recent updates when I searched from my computer settings for some reason.

**Comment by lliangmapiaodang** [comment] 2019-09-22 19:15
2019/9/22
still have the same issue
maybe we should just use git bash for a moment

**Comment by rotwhiler** [comment] 2019-09-25 20:07
Same issue, can't add or remove anything on the Windows feature list.

**Comment by craigloewen-msft** [comment] 2019-09-25 22:50
As an update for this issue: We've been communicating with the team that owns the parts for the optional component install experience and they're aware of this issue and are investigating ways for a general fix. 

In the meantime, I've added a reference to this issue into [troubleshooting.md](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#the-referenced-assembly-could-not-be-found-when-enabling-the-wsl-optional-feature) and compiled some of the solutions that people mentioned on this thread! 

Here's the solution list so far:

* If you are running the enable WSL feature command from PowerShell, try using the GUI instead by opening the start menu, searching for 'Turn Windows features on or off' and then in the list select 'Windows Subsystem for Linux' which will install the optional component.
* Update your version of Windows by going to Settings, Updates, and clicking 'Check for Updates'
* If both of those fail and you need to access WSL please consider upgrading in place by reinstalling Windows 10 using installation media and selecting 'Keep Everything' to ensure your apps and files are preserved. You can find instructions on how to do so at the [Reinstall Windows 10 page](https://support.microsoft.com/en-us/help/4000735/windows-10-reinstall).

**Comment by cheshrkat** [comment] 2019-12-18 04:53
Is there any update on a fix for this? This is blocking WSL usage at my company as the standard installation hits the bug :(

**Comment by KirkBoyd** [comment] 2019-12-18 05:36
@cheshrkat I ended up fixing the issue by updating my Windows 10 image, I was several updates behind. I was a bit nervous going in, but nothing changed, I did not lose any files, and my WSL system worked perfectly afterwards.

**Comment by cheshrkat** [comment] 2019-12-19 23:31
@KirkBoyd unfortunately upgrading to the latest version is not an option in a controlled-installation corporate environment. Our machines are run on older feature builds with security patches applied - pretty common strategy, but one that really messes with WSL.

**Comment by deadpoolknows** [comment] 2020-04-29 15:45
I request everyone to try running it in Administrative mode. That worked for me.

**Comment by anunay-kumar** [comment] 2020-05-02 17:01
I seem to have the same exact and looking at this it appears, this is still not fixed.

**Comment by Leepq** [comment] 2020-05-04 09:29
Having a similar issue as well...

**Comment by cklein27** [comment] 2020-05-08 03:22
This issue persists...
Windows 10 enterprise 
Version 1809
Build 17763.1158

**Comment by zoleng** [comment] 2020-06-18 23:42
I still have this issue too

**Comment by AminAnsarian** [comment] 2020-07-09 16:09
Still have this issue. 
Running as administrator did not help.

**Comment by mjd2012gdg** [comment] 2020-07-09 17:13
I think Microsoft has really dropped the ball on this.  I'll give them a day or two to respond and then post what I did to fix this issue with Microsofts help.  Official Disclaimer:  I don't work for Microsoft and don't warranty or guarantee any of information I share as correct for any given case or that it won't breaks something in the process.

**Comment by saideepesh000** [comment] 2020-07-12 11:06
I still have the issue

**Comment by victorbcn** [comment] 2020-07-14 07:44
> I think Microsoft has really dropped the ball on this. I'll give them a day or two to respond and then post what I did to fix this issue with Microsofts help. Official Disclaimer: I don't work for Microsoft and don't warranty or guarantee any of information I share as correct for any given case or that it won't breaks something in the process.

Please do so, we are several people affected by the issue. Thank you.

**Comment by victorbcn** [comment] 2020-07-14 07:45
> As an update for this issue: We've been communicating with the team that owns the parts for the optional component install experience and they're aware of this issue and are investigating ways for a general fix.
> 
> In the meantime, I've added a reference to this issue into [troubleshooting.md](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#the-referenced-assembly-could-not-be-found-when-enabling-the-wsl-optional-feature) and compiled some of the solutions that people mentioned on this thread!
> 
> Here's the solution list so far:
> 
> * If you are running the enable WSL feature command from PowerShell, try using the GUI instead by opening the start menu, searching for 'Turn Windows features on or off' and then in the list select 'Windows Subsystem for Linux' which will install the optional component.
> * Update your version of Windows by going to Settings, Updates, and clicking 'Check for Updates'
> * If both of those fail and you need to access WSL please consider upgrading in place by reinstalling Windows 10 using installation media and selecting 'Keep Everything' to ensure your apps and files are preserved. You can find instructions on how to do so at the [Reinstall Windows 10 page](https://support.microsoft.com/en-us/help/4000735/windows-10-reinstall).

1st option does not work, and both 2nd and 3rd options are not possible on this company-owned laptop. I would be very interested in knowing the root cause and fixing that, not just using windows update / windows reinstall to regenerate broken files in order to fix it.

**Comment by mjd2012gdg** [comment] 2020-07-14 21:03
**BEFORE YOU PROCEED:

The following is an email chain for fixing the issue I had with installing the linux subsystem on my company's Windows 10.  It is in reverse chronological order.  It may or may not be the same issue and/or solution you need.  YOU are responsible for any damage it causes to your system, so be sure you know what you are doing before running a command.  Also read through the ENTIR conversation before proceeding.  THERE ARE a few emails that I don't have anymore so they are missing, I tried to note where there were.

Lastly, I have done my best to remove contact info so the guys that helped me don't get carpet bombed with email.  If I missed something, be respectful.

- MJD**
-----------------------------------------------------------------

From: "User" <>
Date: Tuesday, June 18, 2019 at 2:29 PM
To: Troy S. <>, Ben H. <>, Craig L. <>
Subject: Re: [MicrosoftDocs/WSL] Error - The referenced assembly could not be found (#368)

Kali Linux installed fine.
 
Thank you again for all your help guys!!  You might want to share your fix instructions in the forum!
 
-	User

 
From: Troy S. <>
Date: Monday, June 17, 2019 at 9:12 PM
To: "User" <>, Ben H. <>, Craig L. <>
Subject: RE: [MicrosoftDocs/WSL] Error - The referenced assembly could not be found (#368)
 
Notice: This email is from an external sender. 
 
That is good news. 
 
Sent from my Windows 10 device

**Comment by craigloewen-msft** [comment] 2021-02-17 19:32
Closing out this issue due to a lack of activity, we haven't seen any new cases of this issue in a while and will keep an eye on this thread if new ones pop up!

**Closed by craigloewen-msft** 2021-02-17 19:32 UTC

**Comment by nagromc** [comment] 2021-03-04 10:01
Well… Sorry to ask @craigloewen-msft, but I encountered the same problem.

```powershell
> wmic os get Caption,Version,BuildNumber /value


BuildNumber=17763
Caption=Microsoft Windows 10 Entreprise LTSC
Version=10.0.17763

> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature : L’assembly référencé n’a pas pu être trouvé.
Au caractère Ligne:1 : 1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
```

Trying to enable the Windows feature _Windows Subsystem for Linux_, the same error code is displayed: `0x80073701`.

My system is up to date. I don’t know if this can help, but please note my company enabled the following group policies:
- Specify intranet Microsoft update service location
- Do not allow update deferral policies to cause scans against Windows Update

**Comment by lbaasheim** [comment] 2021-03-11 07:13
I too am experiencing the exact same issue, on a Windows Server 2019 build 1809. Do you have a solution you can post, please? It has been two years since the original issue was posted, you surely must have something other than reinstalling in place? Installing via GUI has no effect, and the installation is brand new, so updating is not relevant.

**Comment by TehWardy** [comment] 2021-03-20 18:55
Is this Powershell output related to the problem ...

```
PS C:\Users\Paul> dism /Online /NoRestart /English /Enable-Feature /FeatureName:MSMQ-Server /all

Deployment Image Servicing and Management tool
Version: 10.0.17763.1697

Image Version: 10.0.17763.1821

Enabling feature(s)
[==========================100.0%==========================]

Error: 14081

The referenced assembly could not be found.

The DISM log file can be found at C:\windows\Logs\DISM\dism.log
PS C:\Users\Paul> dism /Online /NoRestart /English /Enable-WindowsOptionalFeature /FeatureName:MSMQ-Server /all

Deployment Image Servicing and Management tool
Version: 10.0.17763.1697

Image Version: 10.0.17763.1821


Error: 87

The enable-windowsoptionalfeature option is unknown.
For more information, refer to the help by running DISM.exe /?.

The DISM log file can be found at C:\windows\Logs\DISM\dism.log
PS C:\Users\Paul> Enable-WindowsOptionalFeature -Online -FeatureName MSMQ-Server -All
Enable-WindowsOptionalFeature : The referenced assembly could not be found.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName MSMQ-Server -All
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
```

**Comment by kharyal** [comment] 2021-07-11 05:28
Fixed the issue by directly downloading the latest Windows update from [here](https://www.microsoft.com/en-us/software-download/Windows10). Windows update from settings was throwing error 0x80073701.

**Comment by ahmed98Osama** [comment] 2021-09-30 21:27
Any Solution ?

**Comment by Victor-Gold** [comment] 2022-05-13 18:24
I guess this was never resolved and I am having exactly the same issues and error messages.

**Comment by TehWardy** [comment] 2022-05-14 15:51
My solution was to use a newer powershell version than what comes with windows.
It turns out that dotnet core / dot net 6/7 only runs on newer versions, 
I think it has something to do with the PS build itself.

Hopefully that helps.

It's also worth noting that MSMQ is now a retired technology ... we should be using either Azure Service bus or something like redis with RabbitMQ

**Comment by ohshoot145** [comment] 2023-03-05 09:18
Me too
![Screenshot 2023-03-05 161519](https://user-images.githubusercontent.com/127015739/222952077-0e374373-1769-4f71-9dad-7e71fc07cf2d.png)
