### ISSUE TITLE
Duplicate description text for Install Linux on Windows with WSL page

### ISSUE THREAD

**Issue by Awadhesh43** [MicrosoftDocs/WSL#1696] opened 2022-12-29 09:12 UTC
### Documentation Issue

The below mentioned description under heading Install WSL can be seen twice. May be an update is required to avoid confusion and for better readability purpose.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install#:~:text=be%20changed).-,If%20you%27re%20running%20an%20older%20build%2C%20or%20just%20prefer%20not%20to%20use%20the%20install%20command%20and%20would%20like%20step%2Dby%2Dstep%20directions%2C%20see%20WSL%20manual%20installation%20steps%20for%20older%20versions.,-If%20you%27re%20running

### Suggested Improvements

Commit - fa7237857e13e3c48cce4380b2425e8043878e22

**Comment by phil-blain** [comment] 2022-12-30 13:56
in fact this is a duplicate of #1660

**Comment by craigloewen-msft** [comment] 2023-03-13 18:21
Fixed here! https://github.com/MicrosoftDocs/WSL/pull/1697

**Closed by craigloewen-msft** 2023-03-13 18:21 UTC
